### ISSUE TITLE
Hello, can you ask a question?

### ISSUE THREAD

**Issue by lki2019** [fozzysec/DouyuHLS#1]
For example, I would like to know the IP address of a anchor that is being launched

What method can be used to get it?

![qq 20170728084955](https://user-images.githubusercontent.com/30022431/28697935-3bdffb4c-7372-11e7-9c84-f5f80c07e531.png)

I see someone else can get to the anchor IP address, that is, do not know what method is used

**Comment by fozzysec** [comment]
To get the location of streamer at Douyu, you can get it from API, the returned data is something like this
```
{"error":0,"data":{"use_p2p":"0","show_details":"房管2个火箭   每晚8:00-12:00直播","nickname":"软妹小九九丶","rtmp_url":"http:\/\/hdl3a.douyucdn.cn\/live","ggad":{"play4":"","play1":"","videop":"","play2":"","play5":"","play3":""},"anchor_city":"上海市","specific_status":"1","url":"\/xiaojiujiu",
```
the `["data"]["anchor"]` is just what you need.
The API can be found at (here)[https://gist.github.com/ERioK/d73f76dbb0334618ff905f1bf3363401]

**Comment by lki2019** [comment]
such as:
Https://www.douyu.com/274874 is live
Https://www.douyu.com/2196871 is live

What order?

douyu.py Https://www.douyu.com/274874 ？

-----------------------------------------------------

**Comment by fozzysec** [comment]
The provided link is only for reference, the JSON returned contains the
data that you need, you need to write code to implement it.

**Comment by lki2019** [comment]
http://open.douyucdn.cn/api/RoomApi/room/601774

anchor  And there is no corresponding value

**Comment by lki2019** [comment]
I am not too understand, trouble you!

**Comment by fozzysec** [comment]
The open API is not the API that used to get that JSON data, the open API is just used to get the actual `room_id` when id is not digital. After get the actual id, you need to use the second API to get the JSON data that you need.

**Comment by lki2019** [comment]
Thank you, I have just studied the next,

I added the sentence
print (jdata)

But does not seem to query the IP address

Only show geography   

anchor_city': '南京市',

**Comment by lki2019** [comment]
Thank you very much, I am now going to use the code you wrote under the test

**Comment by lki2019** [comment]
Feedback about it

https://www.douyu.com/607575

py -3 anchor_city.py https://www.douyu.com/607575
Chuo


The return is chuo

The anchor is in Japan

**Comment by lki2019** [comment]
Tested some, some live between the return can not return to geographical location

Anchor IP address, can not return?

Douyu have a private IP address of the anchor anchor?

So get less？

**Comment by fozzysec** [comment]
That's because your system doesn't have Korean language pack installed. I test through your url it works well.
```
python3 location.py https://www.douyu.com/1073540
구로구
```

As for the https://www.douyu.com/607575,
it returns **Chuo** means it is in the Chuo region of Tokyo, Japan. The location is more accurate than you can see from the html page.
P.S.
It is not possible to get the real source ip address of the streamer because douyu hid the ip and only shows the location.

**Comment by lki2019** [comment]
py -3 anchor_city.py http://www.douyu.com/lhds
鱼塘


py -3 anchor_city.py http://www.douyu.com/t/wanxingren
鱼塘


鱼塘？
------------------------------------------------
The current location is not accurate

Now there is no way to make the location more detailed?

**Comment by lki2019** [comment]
servers': [{'ip': '119.90.49.86', 'port'
: '8076'}, {'ip': '119.90.49.88', 'port': '8088'}, {'ip': '119.90.49.87', 'port': '8082'}, {'ip': '119.90.49.87', 'port': '8083'}, {'ip': '119.90.49.89', 'port': '8093'}, {'ip': '119.90.49.90', 'port': '8099'}, {'ip': '119.90.49.86', 'port': '8079'}, {'ip': '119.90.49.101', 'port': '8005'}, {'ip': '119.90.49.106', 'port': '8030'}, {'ip': '119.90.49.106', 'port': '8026'}, {'ip': '119.90.49.102', 'port': '8008'}, {'ip': '119.90.49.90', 'port': '8097'}, {'ip': '119.90.49.104', 'port': '8017'}, {'ip': '119.90.49.110', 'port': '8049'}, {'ip': '119.90.49.93', 'port': '8063'}, {'ip': '119.90.49.101', 'port': '8004'}, {'ip': '119.90.49.91', 'port': '8052'}, {'ip': '119.90.49.88', 'port': '8089'}, {'ip': '119.90.49.108', 'port': '8039'}, {'ip': '119.90.49.101', 'port': '8002'}, {'ip': '119.90.49.94', 'port': '8066'}, {'ip': '119.90.49.90', 'port': '8096'}, {'ip': '119.90.49.102', 'port': '8009'}, {'ip': '119.90.49.94', 'port': '8070'}, {'ip': '119.90.49.109', 'port': '8045'}, {'ip': '119.90.49.91', 'port': '8053'}, {'ip': '119.90.49.108', 'port': '8036'}, {'ip': '119.90.49.109', 'port': '8042'}, {'ip': '119.90.49.104', 'port': '8018'}, {'ip': '119.90.49.92', 'port': '8058'}],



============================

Are these IP addresses the current live servers?

Are different servers allocated between different broadcasts?

**Comment by fozzysec** [comment]
Those ip addrs are just douyu's server address, there are no relationship between those ip and the streamer.
When location is not available, it is just shown as `鱼塘`

**Comment by lki2019** [comment]
Austrian, understand, very grateful!

**Comment by lki2019** [comment]
https://www.douyu.com/105025

height=540
  operation_X264_L=Level52
  operation_X264_P=High
  operation_baseband=G9550ZCU1AQEE
  operation_framerate=24
  operation_loc=50293
  operation_network=MOBILE LTE 13
  operation_phone=samsung SM-G9550 dream2qltezc
  operation_sdk_version=24
  operation_system=DouyuTV android 
  operation_timezone=Europe/Brussels
  operation_version=2.5.2.2
  start_time=Fri Jul 28 20:16:23 2017

  stereo=false
  videocodecid=7
  videodatarate=550
  width=960


------------------------


Is it possible to return to the host phone model or computer configuration?

**Comment by lki2019** [comment]
Ha, my question a little more,

Do not bother you,
Thank you very much for your patience!

**Comment by fozzysec** [comment]
Yes but parsing the Flv metadata is a complex work, you can see [this](http://code.activestate.com/recipes/457406-read-flash-video-flv-files-metadata/) for reference.
If you just need to get the model of mobile phone that used to streaming, you can just get it by
```
streamlink https://www.douyu.com/xxx -O|ffmpeg -i pipe:0
```
P.S.
Desktop streamer may not have the correspond information, only those mobile streams have those kind of information.
Also douyu is good at protecting sensitive information. If you are curious about those kind of information, you can look into huajiao.com
```
{"feed":{"sn":"_LC_XY0_non_5289805415012613031458596_OX","paused":"N","position":"Y","replay_status":0,"m3u8":"","subtitle":"","subtitle_index":"","liveCache":1501267425,"image":"http:\/\/image.huajiao.com\/41c7db152131a5cef8e6708394472358.jpg","publishtime":"2017-07-29 01:01:43","title":"\u597d\u54c8\u54c8\u54c8","tags":[],"duration":"00:00:00","width":504,"height":896,"device":"iPhone 7 Plus","network":"Wi-Fi","all_link":"N","special_room":0,"origin_status":1,"location":"\u56db\u5ddd \u6210\u90fd","point":{"lon":"104.104","lat":"30.633"},"is_link":"N","labels":["\u6e05\u7eaf","\u767d\u9886"],"live_cate":"\u989c\u503c","cate_icon":"http:\/\/img.s3.huajiao.com\/Object.access\/hj-img\/cGhwNWFLdVUw","is_interactive":"Y","is_vr":"N","is_privacy":"N","is_faceu":"Y","sn_ext":"_LC_XY0_non_5289805415012613031458596_OX","is_link_sn":"N","is_song":"Y","share_redpacket":"N","world_redpacket":"Y","link_vice_sn":"","is_game":"N","game":"","is_outdoors":"N","relateid":137961317,"favorited":false,"praises":11319,"watches":23272,"reposts":21,"replies":0,"small_videos":72,"version":0,"privacy_info":{"authorized":"N"},"formated_title":"\u597d\u54c8\u54c8\u54c8","cate_info":{"show_name":"\u989c\u503c","interface_name":"tag_\u989c\u503c","url":"\/category\/800"}},"author":{"uid":"52898054","nickname":"\u5c0f\uff5e\u5c0f\uff5e","avatar":"http:\/\/image.huajiao.com\/41c7db152131a5cef8e6708394472358-100_100.jpg","followed":false,"verified":false,"verifiedinfo":{"credentials":"","type":0,"realname":"\u5c0f\uff5e\u5c0f\uff5e","status":0,"error":"","official":false},"exp":4349148,"level":31,"authorexp":25318,"authorlevel":14,"is_author_task":1,"medal":[{"kind":"tuhao","medal":"4"}],"userCache":1501267420,"userCacheEx":0,"pocket":{"account":{"income":"0","income_b":"11561","income_p":"13653787","uid":"52898054"},"moment_rank":131,"world_redpacket":{"has_redpacket":0,"request_server":0,"verify_code":0,"verify_url":""}}},"type":1,"creatime":"2017-07-29 01:01:43","relay":{"usign":"9b00f52945030f0f5c89b46245264c19","usign_ext":"9b00f52945030f0f5c89b46245264c19","channel":"live_huajiao_v2"},"api_cache":1501267426,"setting":[]}
```
you can even get the accurate GPS location and lookup at http://api.map.baidu.com/lbsapi/getpoint/index.html
There are many stream platform that similar like this, especially LBS stream platform such as inke, huajiao and etc, but douyu, panda is not that weak in security.

**Comment by lki2019** [comment]
Thank you
These are very interesting

**Comment by lki2019** [comment]
You can recommend a few AC video recording, analysis, download,
Is there a live download, parsing, a similar website or forum?

**Comment by fozzysec** [comment]
I don't understand what is the ac video.

**Comment by lki2019** [comment]
You can recommend on video recording, analysis, download,
Is there a live download, parsing, a similar website or forum?


As well as some paid video or live analysis and recording

**Comment by fozzysec** [comment]
For huajiao.com you can use **streamlink**, it works.

**Comment by lki2019** [comment]
Thank you for learning a lot of things with you
